services:
  - type: web
    name: student-election-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: "test"
